Bump dependencies

diff --git a/.github/workflows/check-dependencies.yml b/.github/workflows/check-dependencies.yml
--- a/.github/workflows/check-dependencies.yml
+++ b/.github/workflows/check-dependencies.yml
@@ -1,4 +1,6 @@
 
+# GENERATED: This file is automatically updated by 'Bump dependencies', local changes will be overwritten!
+
 name: 'Check dependencies'
 
 on:
@@ -9,7 +11,7 @@ on:
   pull_request:
   workflow_dispatch:
   schedule:
-    - cron: '0 8 */2 * *'
+    - cron: '0 8 * * Sun'
 
 jobs:
   checks:
@@ -17,29 +19,47 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
-        uses: actions/checkout@v2
-      - name: All changed files
-        id: files
-        if: github.event_name != 'workflow_dispatch' && github.event_name != 'schedule'
-        uses: jitterbit/get-changed-files@v1
+        uses: actions/checkout@v3
         with:
-          format: 'json'
+          fetch-depth: 100
+      - name: Last run
+        uses: nrwl/last-successful-commit-action@v1
+        id: last_successful_commit
+        with:
+          branch: main
+          workflow_id: 'check-dependencies.yml'
+          github_token: "${{ secrets.GITHUB_TOKEN }}"
       - name: Changed?
         id: is_changed
         run: |
           if ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' }}; then
               echo "RUN DEPENDENCY CHECK FOR MANUAL OR SCHEDULED RUN (${{ github.event_name }})"
-              echo "::set-output name=IS_CHANGED::1"
+              echo "IS_CHANGED=1" >> $GITHUB_OUTPUT
+              echo "::notice Dependency check for manual/scheduled run"
               exit 0
           fi
-          readarray -t changed_files <<<"$(jq -r '.[]' <<<'${{ steps.files.outputs.all }}')"
-          for changed_file in ${changed_files[@]}; do
-              if expr "$changed_file" : ".*Dockerfile" || expr "$changed_file" : ".*Cargo\..*" ; then
+          echo "not a scheduled or manual run"
+          basecmt="${{ steps.last_successful_commit.outputs.commit_hash }}"
+          echo "checking if previous run $basecmt can be found"
+          if [ -z "$basecmt" ] || git diff --quiet --exit-code HEAD "$basecmt"
+          then
+              echo "RUN DEPENDENCY CHECK BECAUSE DETERMINING PREVIOUS SUCCESSFUL RUN FAILED (ref = '$basecmt')" 1>&2
+              echo "IS_CHANGED=1" >> $GITHUB_OUTPUT
+              echo "::notice Dependency check because previous run failed"
+              exit 0
+          fi
+          echo "previous run found, checking differences since then"
+          while IFS= read -r changed_file
+          do
+              if [[ "$changed_file" =~ .*Dockerfile$ ]] || [[ "$changed_file" =~ .*Cargo\..* ]]
+              then
                   echo "RUN DEPENDENCY CHECK BECAUSE OF $changed_file"
-                  echo "::set-output name=IS_CHANGED::1"
+                  echo "IS_CHANGED=1" >> $GITHUB_OUTPUT
+                  echo "::notice Dependency check because '$changed_file' changed"
+              else
+                  echo "found changes in $changed_file but not recognized as a dependency file"
               fi
-          done
-
+          done <<< "$(git diff --name-only HEAD "$basecmt")"
       - name: Log
         if: ${{ steps.is_changed.outputs.IS_CHANGED == '1' }}
         run: |
